unamfi/sistop-2026-1

- practicas/1/JuanPerdomo/jakepys.txt
> Add: Agrego el nombre JuanPerdomo

- practicas/1/TejedaAbraham/TejedaAbraham.txt
- practicas/1/TejedaAbraham/tejeda.txt
Entrega de la práctica 1 del curso "Sistemas Operativos".
Se agrega el archivo:
practicas/1/TejedaAbraham/TejedaAbraham.txt
Contenido:
- Título de la práctica
- Fecha de creación y entrega
- Nombre completo
- Usuario en GitHub
Soy Abraham Tejeda, y mi nombre de usuario en GitHub es «Abraham-Tejeda-Vaca».
> Práctica 1 — Abraham Tejeda

- practicas/1/TapiaAndres/Andres.txt
Practica 01 uso de Git y github
Tapia Garcia Andrés
> Practica 01 uso de Git y github

- practicas/1/CoronadoDiego/DiegoCoronado3.txt
Agregué mi carpeta CoronadoPerezDiego en practicas/1
y dentro el archivo DiegoCoronado3.txt con mi nombre y usuario de GitHub.
> Agrego el nombre de Diego Coronado

- practicas/1/MichelleGonzalez/paogmtz.txt
se creo la carpeta Michelle Gonzalez con su respectivo archivo
> Entrega Practica 1

- practicas/1/AvilaAlonso/MonchoPs13.txt
> Entrega Práctica 1

- practicas/1/EchevarriaLuis/LuisEchevarria.txt
Practica 01. Uso de Git y de Github.
Echevarria Aguilar Luis Angel
> Agrego el nombre de Luis Echevarria

- practicas/1/MayaTorresBruno/Maya-Torres-Bruno.txt
Realicé la práctica número uno que consistió en crear un fork y clonar el repositorio para trabajarlo localmente, posteriormente creé un archivo de texto en donde especifico mi nombre real junto con mi nombre de usuario.
> Agrego el nombre de Bruno Maya Torres

- practicas/1/MoralesArumy/arumy.txt
Entrega de práctica 1: creé un archivo arumy.txt con mi nombre real completo y mi nombre de usuario.
> Arumy Lizeth Morales Castillo

- practicas/1/AlvarezEduardo/AlvarezSalgadoEduardoAntonio.txt
- practicas/1/AlvarezSalgadoEduardoAntonio.txt
Entrega de la práctica 1 corregida
> Agrego el nombre de Alvarez Salgado Eduardo Antonio

- practicas/1/TrejoEmmanuel/olveratrech.txt
> Agrego el nombre de Emmanuel Trejo

- practicas/1/ZamoraManuel/ZamoraManuel.txt
Siguiendo los pasos descritos en la práctica 1, creé un archivo de texto indicando mi nombre real y mi nombre de usuario, además, cloné el repositorio de forma local en mi computadora.
> Agrego el nombre de Antonio Manuel Zamora Ayala

- practicas/1/HernandezJosue/HernandezJosue.txt
Agrego el contenido de la práctica 1, con una línea de texto que contiene la frase "Soy Josue Hernandez, y mi nombre de usuario es Herjoru1"
> Agrego el nombre de Josue Hernandez

- practicas/2/EchevarriaLuis/cpuinfo.txt
Agrego el archivo cpuinfo.txt de Luis Echevarria para la prática 2B.
> Agrego el archivo de Luis Echevarria para la práctica 2B

- practicas/2/TapiaAngel/cpuinfo.txt
Agrego el archivo de Angel Tapia para la practica 2B
> Agrego el archivo de Angel Tapia para la practica 2B

- practicas/2/AlvarezEduardo/cpuinfo.txt
Práctica 2B archivo de texto con información del dispositivo
> Agrego el archivo de AlvarezEduardo para la práctica 2B

- practicas/2/JimenezEvelin/cpuinfo.txt
Práctica 2B – Archivo de Evelin Jimenez
> Agrego el archivo de Evelin Jimenez para la practica 2B

- practicas/2/README.md
> Corrección de typo en el readme de la práctica 2

- practicas/3/LunaDiego/saludo.py
> Entrega Práctica 3 - Luna Diego

- practicas/3/TejedaAbraham/saludo.c
Entrego P3
- Archivo único: practicas/3/TejedaAbraham/saludo.c
- Commits: 
1) P3: estado inicial - hola mundo
2) P3: estado final - saludo con nombre (argv)
- Evidencias:
> Práctica 3 - Tejeda Abraham
